/**
 * =============================================================================
 * File: dsa-page.js
 * Path: js/notes/dsa/dsa-page.js
 * Project: Learning Dashboard
 *
 * Description:
 * Boot entry point for DSA note pages. Calls
 * NotesPageCore.init({subjectLabel:'DSA', extraModules, extraInit}) — adds
 * 5 DSA-only modules (dsa-visualisation.js, dsa-problems.js,
 * dsa-contest.js, dsa-visual-mcq.js, dsa-print.js) on top of the 11 shared
 * notes/*.js scripts, plus the code-language-tab UI that AWS notes don't
 * use. Dynamically loaded by notes-page-core.js based on
 * <body data-subject="dsa">. Requires notes-page-core.js loaded first.
 *
 * Each module is tagged with a category (see notes-page-core.js's
 * MODULE_REGISTRY doc) so notes-page-core.js can decide what to skip in
 * Lite Mode and what to stamp for print, without either concern needing
 * DSA-specific knowledge baked into it:
 *   - dsa-visualisation.js / dsa-visual-mcq.js: 'interactive'
 *   - dsa-problems.js / dsa-contest.js: 'links' (LeetCode/contest tables)
 *   - dsa-print.js: 'core' (print itself must survive Lite Mode)
 *
 * Author: Namrata Mulwani
 * Created: —
 * Last Updated: 2026-07-05
 *
 * Dependencies:
 * - js/notes/notes-page-core.js (must load first)
 * - window.SiteConfig (js/shared/site-config.js)
 * =============================================================================
 */

(function () {
    'use strict';

    const dsaBase = window.SiteConfig.dsaPath('');

    const dsaModules = [
        { file: 'dsa-visualisation.js', category: 'interactive', containerSelector: '.viz-panel', label: 'Visualisation' },
        { file: 'dsa-problems.js',      category: 'links',       containerId: 'problemsContainer', label: 'LeetCode Problems' },
        { file: 'dsa-contest.js',       category: 'links',       containerId: 'contestContainer', label: 'Contest Problems' },
        { file: 'dsa-visual-mcq.js',    category: 'interactive', containerId: 'visualMcqContainer', label: 'Visual Questions' },
        { file: 'dsa-print.js',         category: 'core' }
    ].map(m => Object.assign({}, m, { src: `${dsaBase}/${m.file}` }));

    // Print-only entry: the Implementation section's code-language tabs
    // are wired up below by initCodeTabs (not a separate loaded script),
    // but still need to be categorized as interactive for notes-print.js —
    // no `src`, so notes-page-core.js's init() will categorize it for
    // print without ever treating it as loadable/skippable.
    dsaModules.push({ category: 'interactive', containerSelector: '.code-tab-bar', label: 'Implementation' });

    // Also static/script-less — generated by generate_notes.py, DSA-only
    // (AWS pages don't have this section, so it's registered here rather
    // than in the shared notes-page-core.js registry). "youtube-
    // recommendations" is the `id` on the section's <h2>, same as
    // Links & References — not a class on any div.
    dsaModules.push({ category: 'links', containerId: 'youtube-recommendations', label: 'YouTube Recommendations' });

    function initCodeTabs(liteMode) {
        // notes-page-core.js already placeholder'd every .code-tab-bar
        // (there can be more than one per page) when Lite Mode is on, so
        // there's nothing left to wire up — skip entirely instead of
        // attaching click handlers to elements that no longer exist.
        if (liteMode) return;

        document.querySelectorAll('.code-tab-bar').forEach(function (bar) {
            const tabs = bar.querySelectorAll('.code-tab');
            const panelGroup = bar.parentElement;

            tabs.forEach(function (tab) {
                tab.addEventListener('click', function () {
                    const lang = tab.dataset.lang;

                    tabs.forEach(function (t) {
                        t.classList.remove('active');
                        t.setAttribute('aria-selected', 'false');
                    });
                    tab.classList.add('active');
                    tab.setAttribute('aria-selected', 'true');

                    panelGroup.querySelectorAll('.code-panel').forEach(function (panel) {
                        const isMatch = panel.id === `code-${lang}`;
                        panel.classList.toggle('active', isMatch);
                        panel.style.display = isMatch ? '' : 'none';
                    });
                });
            });
        });
    }

    window.NotesPageCore.init({
        subjectLabel: 'DSA',
        extraModules: dsaModules,
        extraInit: initCodeTabs
    });

})();
